CREATE TABLE USERS(
      USER_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
      EMAIL VARCHAR(100) NOT NULL UNIQUE,
      PHONENUMBER(15),
      USERNAME VARCHAR(50) NOT NULL,
      ADDRESS VARCHAR(255),
      PASSWORD VARCHAR(100) NOT NULL
);
CREATE TABLE ORDERS(
      ORDER_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
      USER_ID INTEGER,
      TOTAL_AMOUNT DECIMAL(10,2),
      STATUS VARCHAR(20) DEFAULT 'PENDING',
      FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
